# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np    

print(np.__version__)


1.26.0


2) Создать нулевой вектор размера 10

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [5]:
np.full(7,7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [10]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [98]:
array = np.random.randint(1, 10, size=(np.random.randint(6,10)))
print("Normal - {}". format(array))
print("Reversed - {}". format(array[::-1]))


Normal - [4 4 3 8 5 4]
Reversed - [4 5 8 3 4 4]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [18]:
arr = np.arange(9)
arr = arr.reshape(3,3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [82]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [174]:
s = np.diag([1,2,3,4])
for i in range(s.shape[0]):
    for n in range(s.shape[1]):
        if i != n:
            s[i][n] = 7

print(s)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]
range(0, 4)


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [103]:
s = np.full((5,5),[0,1,2,3,4]) 

print(s)       
  

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [188]:

s = np.random.randint(1,10, size=(10,10))
meanmat = s.mean(axis=1)
z = s - meanmat

print(s)
print(meanmat)
print(z)


[[2 4 6 4 2 8 8 3 1 3]
 [8 3 7 6 2 2 3 6 2 6]
 [9 7 9 7 7 6 8 6 2 7]
 [5 6 6 7 6 3 2 6 8 6]
 [3 8 9 4 3 3 8 9 5 9]
 [9 8 4 5 7 9 8 4 9 5]
 [7 7 9 4 8 2 1 2 3 4]
 [9 1 5 2 8 2 5 7 9 8]
 [9 4 5 8 3 9 1 2 9 3]
 [7 7 4 2 6 4 3 6 8 3]]
[4.1 4.5 6.8 5.5 6.1 6.8 4.7 5.6 5.3 5. ]
[[-2.1 -0.5 -0.8 -1.5 -4.1  1.2  3.3 -2.6 -4.3 -2. ]
 [ 3.9 -1.5  0.2  0.5 -4.1 -4.8 -1.7  0.4 -3.3  1. ]
 [ 4.9  2.5  2.2  1.5  0.9 -0.8  3.3  0.4 -3.3  2. ]
 [ 0.9  1.5 -0.8  1.5 -0.1 -3.8 -2.7  0.4  2.7  1. ]
 [-1.1  3.5  2.2 -1.5 -3.1 -3.8  3.3  3.4 -0.3  4. ]
 [ 4.9  3.5 -2.8 -0.5  0.9  2.2  3.3 -1.6  3.7  0. ]
 [ 2.9  2.5  2.2 -1.5  1.9 -4.8 -3.7 -3.6 -2.3 -1. ]
 [ 4.9 -3.5 -1.8 -3.5  1.9 -4.8  0.3  1.4  3.7  3. ]
 [ 4.9 -0.5 -1.8  2.5 -3.1  2.2 -3.7 -3.6  3.7 -2. ]
 [ 2.9  2.5 -2.8 -3.5 -0.1 -2.8 -1.7  0.4  2.7 -2. ]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [202]:
matrix = np.random.randint(1,10, size=(10,10))
matrixmed = np.median(matrix, axis=0)
z =matrix-matrixmed 
print(matrix)
print(matrixmed)
print(z)

[[5 2 4 1 5 8 3 7 9 9]
 [3 1 4 1 9 7 2 7 8 2]
 [5 4 4 5 2 5 1 1 7 1]
 [2 2 6 3 8 3 6 2 2 4]
 [4 2 5 7 1 3 3 1 6 1]
 [3 7 9 2 1 2 3 1 7 9]
 [9 2 3 3 2 5 8 6 5 1]
 [2 4 7 3 2 6 5 7 6 8]
 [8 6 3 3 6 3 6 2 3 8]
 [4 2 2 2 8 3 4 2 8 5]]
[4.  2.  4.  3.  3.5 4.  3.5 2.  6.5 4.5]
[[ 1.   0.   0.  -2.   1.5  4.  -0.5  5.   2.5  4.5]
 [-1.  -1.   0.  -2.   5.5  3.  -1.5  5.   1.5 -2.5]
 [ 1.   2.   0.   2.  -1.5  1.  -2.5 -1.   0.5 -3.5]
 [-2.   0.   2.   0.   4.5 -1.   2.5  0.  -4.5 -0.5]
 [ 0.   0.   1.   4.  -2.5 -1.  -0.5 -1.  -0.5 -3.5]
 [-1.   5.   5.  -1.  -2.5 -2.  -0.5 -1.   0.5  4.5]
 [ 5.   0.  -1.   0.  -1.5  1.   4.5  4.  -1.5 -3.5]
 [-2.   2.   3.   0.  -1.5  2.   1.5  5.  -0.5  3.5]
 [ 4.   4.  -1.   0.   2.5 -1.   2.5  0.  -3.5  3.5]
 [ 0.   0.  -2.  -1.   4.5 -1.   0.5  0.   1.5  0.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [246]:
a = np.random.randint(1, 10, (5, 5))
mx = np.array([a.max(axis=1)])
mn = np.array([a.min(axis=1)])

res = np.hstack((a, mx.T, mn.T))
res


array([[3, 4, 5, 6, 9, 9, 3],
       [7, 7, 9, 8, 7, 9, 7],
       [7, 6, 2, 8, 5, 8, 2],
       [9, 1, 9, 9, 2, 9, 1],
       [3, 1, 4, 1, 2, 4, 1]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [287]:
x = np.arange(1,51)
even = np.array(x[1::2])
odd = np.array(x[::2])
print(odd)
print(even)
z=np.outer(even, odd)
det = np.linalg.det(z)
#Определитель равен 0, обратной матрицы нет
result = np.linalg.inv(z)
result




[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


LinAlgError: Singular matrix

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [252]:
zm = np.zeros((8,8))
for i in range(zm.shape[0]):
    for x in range(zm.shape[1]):
        if (i+x) % 2 == 0:
            zm[i][x] = 0
        else:
            zm[i][x] = 1
zm

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])